security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    # Definimos de d√≥nde vienen los usuarios
    providers:
        app_user_provider:
            entity:
                class: App\Auth\Domain\Entity\User
                property: email

    firewalls:
        # Ensure dev tools and static assets are always allowed
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false

        # Cortafuegos principal de la API
        api:
            pattern: ^/api
            stateless: true
            jwt: ~ # Activa el bundle de LexikJWT para validar el token

        # main:
        #     lazy: true
        #     provider: app_user_provider

            # Activate different ways to authenticate:
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Note: Only the *first* matching rule is applied
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/api/auth, roles: PUBLIC_ACCESS }
        - { path: ^/api/doc, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            # Password hashers are resource-intensive by design to ensure security.
            # In tests, it's safe to reduce their cost to improve performance.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
